const products = [
  {
    id: 1,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-1.png",
  },
  {
    id: 2,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-2.png",
  },
  {
    id: 3,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-3.png",
  },
  {
    id: 4,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-4.png",
  },
  {
    id: 5,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-5.png",
  },
  {
    id: 6,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-6.png",
  },
  {
    id: 7,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-7.png",
  },
  {
    id: 8,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-8.png",
  },
  {
    id: 9,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-9.png",
  },
  {
    id: 10,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-10.png",
  },
  {
    id: 11,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-11.png",
  },
  {
    id: 12,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-12.png",
  },
  {
    id: 13,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-13.png",
  },
  {
    id: 14,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-14.png",
  },
  {
    id: 15,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-15.png",
  },
  {
    id: 16,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-16.png",
  },
  {
    id: 17,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-17.png",
  },
  {
    id: 18,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-18.png",
  },
  {
    id: 19,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-19.png",
  },
  {
    id: 20,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-20.png",
  },
  {
    id: 21,
    name: "Tas Ecobag Parasut",
    price: 49999,
    image: "images/products/bag-21.png",
  },
];

export default products;
